[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
version = 2

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
]
confidence-threshold = 0.8
exceptions = []

[bans]
allow = []
allow-wildcard-paths = true
deny = [
    # https://github.com/briansmith/ring/issues/774
    { name = "ring" },
]
highlight = "all"
multiple-versions = "warn"
skip = []
skip-tree = []
# Lint level for when a crate version requirement is `*`
wildcards = "deny"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
