[package]
authors.workspace = true
categories = ["finance", "localization", "no-std", "no-std::no-alloc"]
description = "ISO 10383 Types"
documentation = "https://docs.rs/iso10383-types"
edition.workspace = true
keywords = ["iso10383", "mic"]
license.workspace = true
name = "iso10383-types"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
alloc = ["iso3166-static/alloc", "serde?/alloc", "zerocopy?/alloc"]
default = ["alloc", "serde"]
serde = ["dep:serde", "iso3166-static/serde"]
zerocopy = ["dep:zerocopy"]

[dependencies]
iso3166-static.workspace = true
ref-cast = "1.0"
serde = { features = ["derive"], optional = true, workspace = true }
zerocopy = { optional = true, workspace = true }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
